config/routes.rb
Rails.application.routes.draw do
  devise_for :external_users, controllers: { registrations: 'registrations' }
  devise_for :northwestern_users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'login', to: 'users#login'

  resources :disburser_requests, only: :index, path: 'requests' do
    collection do
      get :admin
      get :data_coordinator
      get :specimen_coordinator
      get :committee
    end

    member do
      get :edit_admin_status
      get :edit_committee_review
      get :edit_data_status
      get :edit_specimen_status
      patch :admin_status
      patch :data_status
      patch :specimen_status
      patch :cancel
    end
    resources :disburser_request_votes
  end

  resources :repositories do
    resources :repository_users
    resources :disburser_requests, except: :index, path: 'requests' do
      member do
        get :download_file
      end
    end
    resources :specimen_types, only: :index do
      collection do
        patch :bulk_update
      end
    end
    member do
      get :download_file
    end

    resource :content, only: [:edit, :update]
  end

  resources :users, only: [:index, :show]

  root 'home#index'
end

app/models/repository.rb
class Repository < ApplicationRecord
  has_paper_trail
  has_many :repository_users
  has_many :users, through: :repository_users
  accepts_nested_attributes_for :repository_users, reject_if: :all_blank, allow_destroy: true
  has_many :specimen_types, -> { order(:name) }
  accepts_nested_attributes_for :specimen_types, allow_destroy: true
  has_many :disburser_requests

  mount_uploader :irb_template, IrbTemplateUploader
  mount_uploader :data_dictionary, DataDictionaryUploader
  mount_uploader :custom_request_form, CustomRequestFormUploader

  validates_presence_of :name
  validates_size_of :irb_template, maximum: 10.megabytes, message: 'must be less than 10MB'
  validates_size_of :data_dictionary, maximum: 10.megabytes, message: 'must be less than 10MB'
  validates_size_of :custom_request_form, maximum: 10.megabytes, message: 'must be less than 10MB'

  after_destroy :remove_irb_template!, :remove_data_dictionary!, :remove_custom_request_form!

  scope :search_across_fields, ->(search_token, options={}) do
    if search_token
      search_token.downcase!
    end
    options = { sort_column: 'name', sort_direction: 'asc' }.merge(options)

    if search_token
      s = where(["lower(name) like ?", "%#{search_token}%"])
    end

    sort = options[:sort_column] + ' ' + options[:sort_direction] + ', repositories.id ASC'
    s = s.nil? ? order(sort) : s.order(sort)

    s
  end

  scope :is_public, -> do
    where(public: true)
  end

  def repository_administrator?(user)
    repository_users.where(user_id: user.id, administrator: true).any?
  end

  def committee_member?(user)
    repository_users.where(user_id: user.id, committee: true).any?
  end

  def repository_coordinator?(user)
    repository_users.where('user_id = ? AND (data_coordinator = ? OR specimen_coordinator = ?)', user.id, true, true).any?
  end

  def data_coordinator?(user)
    repository_users.where('user_id = ? AND data_coordinator = ?', user.id, true).any?
  end

  def specimen_coordinator?(user)
    repository_users.where('user_id = ? AND specimen_coordinator = ?', user.id, true).any?
  end

  def repository_administrators(options={})
    options.reverse_merge!(include_system_administrtors: false)
    administrators = repository_users.where(administrator: true).map(&:user)
    if options[:include_system_administrtors]
      administrators.concat(User.where(system_administrator: true))
    end
    administrators.uniq!
    administrators
  end

  def committee_members
    cm = repository_users.where(committee: true).map(&:user)
    cm
  end

  def specimen_coordinators
    sc = repository_users.where(specimen_coordinator: true).map(&:user)
    sc
  end

  def data_coordinators
    dc = repository_users.where(data_coordinator: true).map(&:user)
    dc
  end

  def unpublished_content?
    (general_content != general_content_published) || (data_content != data_content_published) || (specimen_content != specimen_content_published)
  end

  def publish_content!
    self.general_content_published = self.general_content
    self.data_content_published = self.data_content
    self.specimen_content_published = self.specimen_content
    save!
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :download_file]
  before_action :load_repository, only: [:edit, :show, :update, :download_file]
  helper_method :sort_column, :sort_direction

  def index
    authorize Repository
    params[:page]||= 1
    options = {}
    options[:sort_column] = sort_column
    options[:sort_direction] = sort_direction

    if current_user.system_administrator
      r = Repository
    else
      r = current_user.repositories
    end
    @repositories = r.search_across_fields(params[:search], options).paginate(per_page: 10, page: params[:page])
  end

  def new
    authorize Repository
    @repository = Repository.new()
  end

  def create
    authorize Repository
    @repository = Repository.new(repository_params)

    if @repository.save
      flash[:success] = 'You have successfully created a repository.'
      redirect_to edit_repository_url(@repository)
    else
      flash.now[:alert] = 'Failed to create repository.'
      render action: 'new'
    end
  end

  def show
    authorize @repository
  end

  def edit
    authorize @repository
  end

  def update
    authorize @repository
    if @repository.update_attributes(repository_params)
      flash[:success] = 'You have successfully updated a repository.'
      redirect_to edit_repository_url(@repository)
    else
      flash.now[:alert] = 'Failed to update repository.'
      render action: 'edit'
    end
  end

  def download_file
    case params[:file_type]
    when 'custom_request_form'
      file = @repository.custom_request_form.path
    when 'data_dictionary'
      file = @repository.data_dictionary.path
    when 'irb_template'
      file = @repository.irb_template.path
    end

    return send_file file, disposition: 'attachment', x_sendfile: true unless file.blank?
  end

  private
    def repository_params
      params.require(:repository).permit(:name, :public, :custom_request_form, :custom_request_form_cache, :remove_custom_request_form, :irb_template, :irb_template_cache, :remove_irb_template, :data_dictionary, :data_dictionary_cache, :remove_data_dictionary, :committee_email_reminder, :notify_repository_administrator,  specimen_types_attributes: [:id, :name, :_destroy])
    end

    def load_repository
      @repository = Repository.find(params[:id])
    end

    def sort_column
      ['name'].include?(params[:sort]) ? params[:sort] : 'name'
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
end

app/views/repositories/_navigation.html.haml
.row
  %ul.details.menu
    %li.repository{ class: "#{active?('active', controller: 'repositories', action: 'edit', id: @repository.id)}#{active?('active', controller: 'repositories', action: 'update', id: @repository.id)}" }
      = link_to 'Details', edit_repository_url(@repository), { class: 'edit_repository_link' }
    %li.repository_content{ class: "#{active?('active', controller: 'contents', action: 'edit', repository_id: @repository.id)}#{active?('active', controller: 'contents', action: 'update', repository_id: @repository.id)}" }
      = link_to 'Content', edit_repository_content_url(@repository), { class: 'edit_repository_content_link' }
    %li.repository_users{ class: active?('active', controller: 'repository_users', action: 'index', repository_id: @repository.id) }
      = link_to 'Users', repository_repository_users_url(@repository), { class: 'repository_repository_users_link' }
    %li.specimen_types{ class: "#{active?('active', controller: 'specimen_types', action: 'index', repository_id: @repository.id)}#{active?('active', controller: 'specimen_types', action: 'bulk_update', repository_id: @repository.id)}" }
      = link_to 'Specimen Types', repository_specimen_types_url(@repository), { class: 'repository_specimen_types_link' }

app/views/repositories/_repository.html.haml
.row
  .name
    %div{class: 'small-14 large-4 columns' }
      %label{for: 'repository_name' }
        Name
        %span{ class: 'required' }
    %div{class: 'small-10 large-20 columns' }
      = f.text_field :name
      - if validation_errors?(repository, :name)
        %p.error= format_validation_errors(repository, :name)
.row
  .public
    %div{class: 'small-14 large-4 columns' }
      %label{for: 'repository_public' }
        Public?
    %div{class: 'small-10 large-20 columns' }
      = f.check_box :public
      %span{ class: 'help-text' }
        (Checking this field makes the repository publicly visible to visiting users.)
.row
  .committee_email_reminder
    %div{class: 'small-14 large-4 columns' }
      %label{for: 'repository_committee_email_reminder' }
        Committee email reminder?
    %div{class: 'small-10 large-20 columns' }
      = f.check_box :committee_email_reminder
      %span{ class: 'help-text' }
        (Checking this enables a weekly email reminder to committee members to vote on outstanding requests older than 7 days old.)
.row
  .notify_repository_administrator
    %div{class: 'small-14 large-4 columns' }
      %label{for: 'repository_notify_repository_administrator' }
        Notify Repository Administrator?
    %div{class: 'small-10 large-20 columns' }
      = f.check_box :notify_repository_administrator
      %span{ class: 'help-text' }
        (Checking this enables repository administrators to be carbon copied on all email notifications.)
.row
  .irb_template
    %div{class: 'small-14 large-4 columns' }
      %label{for: 'repository_irb_template' }
        IRB Template
    %div{class: 'small-10 large-20 columns' }
      %div
        - if repository.irb_template? && !repository.new_record?
          = link_to download_file_repository_url(repository, file_type: 'irb_template'), 'data-turbolinks' => false, class: 'irb_template_url' do
            %i
            = repository.irb_template.file.filename
        - if repository.irb_template? && repository.new_record?
          = link_to repository.irb_template.identifier, "#{repository.irb_template.url}",  class: 'irb_template_url'
        = f.file_field :irb_template
        = f.hidden_field :irb_template_cache
        - if repository.irb_template? && !repository.new_record?
          %label{for: 'repository_remove_irb_template' }
            Remove file
            = f.check_box :remove_irb_template
.row
  .data_dictionary
    %div{class: 'small-14 large-4 columns' }
      %label{for: 'repository_data_dictionary' }
        Data Dictionary
    %div{class: 'small-10 large-20 columns' }
      %div
        - if repository.data_dictionary? && !repository.new_record?
          = link_to download_file_repository_url(repository, file_type: 'data_dictionary'), 'data-turbolinks' => false, class: 'data_dictionary_url' do
            %i
            = repository.data_dictionary.file.filename
        - if repository.data_dictionary? && repository.new_record?
          = link_to repository.data_dictionary.identifier, "#{repository.data_dictionary.url}", class: 'data_dictionary_url'
        = f.file_field :data_dictionary
        = f.hidden_field :data_dictionary_cache
        - if repository.data_dictionary? && !repository.new_record?
          %label{for: 'repository_remove_data_dictionary' }
            Remove file
            = f.check_box :remove_data_dictionary
.row
  .custom_request_form
    %div{class: 'small-14 large-4 columns' }
      %label{for: 'repository_custom_request_form' }
        Custom Request Form
    %div{class: 'small-10 large-20 columns' }
      %div
        - if repository.custom_request_form? && !repository.new_record?
          = link_to download_file_repository_url(repository, file_type: 'custom_request_form'), 'data-turbolinks' => false, class: 'custom_request_form_url' do
            %i
            = repository.custom_request_form.file.filename
        - if repository.custom_request_form? && repository.new_record?
          = link_to repository.custom_request_form.identifier, "#{repository.custom_request_form.url}", class: 'custom_request_form_url'
        = f.file_field :custom_request_form
        = f.hidden_field :custom_request_form_cache
        - if repository.custom_request_form? && !repository.new_record?
          %label{for: 'repository_remove_custom_request_form' }
            Remove file
            = f.check_box :remove_custom_request_form

app/views/repositories/edit.html.haml
- content_for(:title) do
  Edit Repository

#edit_repository
  %h4
    = "Repository: #{@repository.name}"
  = render 'repositories/navigation'
  = form_for @repository, html: { class: 'repository_form', multipart: true } do |f|
    = render 'repository', repository: @repository, f: f
    .navigation{class: 'small-offset-12 small-12 large-offset-20 large-4 columns' }
      %p.help-text
        %span{ class: 'required' }
        Indicates required field
      = f.submit 'Save', class: 'button'
      = link_to 'Cancel', repositories_url, class: 'cancel-link button warning'

app/views/repositories/index.html.haml
- content_for(:title) do
  Repositories

#repositories
  .repositories_header
    = form_tag repositories_url, method: 'get', id: 'search_repositories_form'  do
      %h4{ class: 'large-4 columns' }
        Repositories
      .search_box{ class: 'large-offset-8 large-8 columns' }
        %label{for: 'search' }
          Search
        = text_field_tag :search, (params[:search].nil? ? '' : params[:search]), type: 'search'
      .search_buttons{ class: 'large-4 columns' }
        %button{ type: 'submit', id: 'search_repositories_button', class: 'tiny button' }
          Search
        = link_to 'Clear', repositories_url(mine: params[:mine])
  .repositories_list
    = will_paginate @repositories, renderer: FoundationPagination::Rails
    %table.hack_stack
      %thead
        %tr
          %th.name
            = sortable 'name'
          %th.edit
      %tbody
        - @repositories.each do |respository|
          = content_tag_for(:tr, respository) do
            %td.name
              = respository.name
            %td.edit
              = link_to 'Edit', edit_repository_url(respository), { class: 'edit_repository_link' }
    = will_paginate @repositories, renderer: FoundationPagination::Rails
    - if policy(Repository).new?
      = link_to 'New Repository', new_repository_url(), { class: 'new_repository_link' }

app/views/repositories/new.html.haml
- content_for(:title) do
  New Repository
#new_repository
  %h4
    New Repository
  = form_for @repository, html: { class: 'repository_form', multipart: true  } do |f|
    = render 'repository', repository: @repository, f: f
    .navigation{class: 'small-offset-12 small-12 large-offset-20 large-4 columns' }
      %p.help-text
        %span{ class: 'required' }
        Indicates required field
      = f.submit 'Next', class: 'button'
      = link_to 'Cancel', repositories_url, class: 'cancel-link button warning'

app/views/repositories/show.html.haml
- content_for(:title) do
  = "Repository: #{@repository.name}"
#repository
  %h2
    = "Repository: #{@repository.name}"
  .row
    .files
      .user_guide{ class: 'small-6 large-6 columns text-left' }
        Check out the
        = link_to 'user guide.', '/disburser_investigator_submitter_user_guide.pdf', target: '_blank'
      .data_dictionary{ class: 'small-4 large-4 columns text-right' }
        - if @repository.data_dictionary?
          %label{for: 'repository_data_dictionary' }
            Data Dictionary
            = link_to download_file_repository_url(@repository, file_type: 'data_dictionary'), 'data-turbolinks' => false, class: 'data_dictionary_url' do
              %i
                = @repository.data_dictionary.file.filename
      .irb_template{ class: 'small-4 large-4 columns text-right' }
        - if @repository.irb_template?
          %label{for: 'repository_irb_template' }
            IRB Template
          = link_to download_file_repository_url(@repository, file_type: 'irb_template'), 'data-turbolinks' => false, class: 'irb_template_url' do
            %i
              = @repository.irb_template.file.filename
      .custom_request_form{ class: 'small-4 large-4 columns text-right' }
        - if @repository.custom_request_form?
          %label{for: 'repository_custom_request_form' }
            Custom Request Form
          = link_to download_file_repository_url(@repository, file_type: 'custom_request_form'), 'data-turbolinks' => false, class: 'custom_request_form_url' do
            %i
              = @repository.custom_request_form.file.filename
      .new_request{ class: 'small-4 large-4 columns text-right' }
        = link_to 'Make a request!', new_repository_disburser_request_url(@repository), { class: 'button new_repository_request_link' }
  .row
    .general_content_header{ class: 'small-24 columns' }
      %b
        General
  .row
    .general_content{ class: 'small-24 columns' }
      = raw @repository.general_content_published
  .row
    .specimen_content_header{ class: 'small-24 columns' }
      %b
        Specimen
  .row
    .specimen_content{ class: 'small-24 columns' }
      = raw @repository.specimen_content_published
  .row
    .data_content_header{ class: 'small-24 columns' }
      %b
        Data
  .row
    .data_content{ class: 'small-24 columns' }
      = raw @repository.data_content_published