config/routes.rb
Rails.application.routes.draw do
  devise_for :external_users, controllers: { registrations: 'registrations' }
  devise_for :northwestern_users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'login', to: 'users#login'

  resources :disburser_requests, only: :index, path: 'requests' do
    collection do
      get :admin
      get :data_coordinator
      get :specimen_coordinator
      get :committee
    end

    member do
      get :edit_admin_status
      get :edit_committee_review
      get :edit_data_status
      get :edit_specimen_status
      patch :admin_status
      patch :data_status
      patch :specimen_status
      patch :cancel
    end
    resources :disburser_request_votes
  end

  resources :repositories do
    resources :repository_users
    resources :disburser_requests, except: :index, path: 'requests' do
      member do
        get :download_file
      end
    end
    resources :specimen_types, only: :index do
      collection do
        patch :bulk_update
      end
    end
    member do
      get :download_file
    end

    resource :content, only: [:edit, :update]
  end

  resources :users, only: [:index, :show]

  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :repository_users
  has_many :repositories, through: :repository_users
  has_many :disburser_requests, foreign_key: :submitter_id

  validates :email, uniqueness: true, :allow_blank => true

  USER_TYPE_NORTHWESTERN = 'Northwestern'
  USER_TYPE_EXTERNAL = 'External'
  USER_TYPES = [USER_TYPE_NORTHWESTERN, USER_TYPE_EXTERNAL]

  def admin?
    self.system_administrator || repository_administrator?
  end

  def committee?
    repository_users.any? { |repository_user| repository_user.committee }
  end

  def repository_administrator?
    repository_users.any? { |repository_user| repository_user.administrator }
  end

  def data_coordinator?
    repository_users.any? { |repository_user| repository_user.data_coordinator }
  end

  def specimen_coordinator?
    repository_users.any? { |repository_user| repository_user.specimen_coordinator }
  end

  def repository_coordinator?
    repository_users.any? { |repository_user| repository_user.specimen_coordinator ||  repository_user.data_coordinator }
  end

  def full_name
    [first_name.titleize, last_name.titleize].reject { |n| n.nil? or n.blank? }.join(' ')
  end

  def data_coordinator_disbursr_requests(options = {})
    cdr = DisburserRequest.joins(:submitter).joins(:repository).where(repository_id: repository_users.where('data_coordinator = ?', true).map(&:repository_id))

    if options[:status].present?
      cdr = cdr.by_status(options[:status])
    end

    if options[:data_status].present?
      cdr = cdr.by_data_status(options[:data_status])
    end

    if options[:specimen_status].present?
      cdr = cdr.by_specimen_status(options[:specimen_status])
    end

    cdr.not_draft
  end

  def specimen_coordinator_disbursr_requests(options = {})
    sdr = DisburserRequest.joins(:submitter).joins(:repository).where(repository_id: repository_users.where('specimen_coordinator = ?', true).map(&:repository_id))

    if options[:status].present?
      sdr = sdr.by_status(options[:status])
    end

    if options[:data_status].present?
      sdr = sdr.by_data_status(options[:data_status])
    end

    if options[:specimen_status].present?
      sdr = sdr.by_specimen_status(options[:specimen_status])
    end

    sdr.not_draft
  end

  def admin_disbursr_requests
    if self.system_administrator
      adr = DisburserRequest
    else
      adr = DisburserRequest.where(repository_id: repository_users.where('administrator = ?', true).map(&:repository_id))
    end
    adr.not_draft
  end

  def committee_disburser_requests(options = {})
    cdr = DisburserRequest.joins(:submitter).joins(:repository).where(repository_id: repository_users.where('committee = ?', true).map(&:repository_id))

    if options[:status].present?
      cdr = cdr.by_status(options[:status])
    end

    cdr.reviewable.by_feasibility(false)
  end

  def self.search(search_token, repository = nil)
    users = NorthwesternUser.search(search_token, repository)
    users.concat(ExternalUser.search(search_token, repository))
    users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :login
  before_action :load_repository, only: :index
  before_action :load_user, only: :show

  def index
    params[:page]||= 1
    @all_users = User.search(params[:q], @repository)
    @users = @all_users.paginate(per_page: 10, page: params[:page])
    respond_to do |format|
        format.json {
          render json: {
            users: @users,
            total: @all_users.count,
            links: { self: @users.current_page , next: @users.next_page }
        }.to_json
      }
    end
  end

  def show
  end

  def sigin_in
  end

  private
    def load_repository
      @repository = Repository.find(params[:repository_id])
    end

    def load_user
      @user = User.find(params[:id])
    end
end

app/views/users/_login.html.haml
.northwestern_net_id_question{ class: 'large-24 columns text-center lead' }
  %h1
    Do you have a Northwestern NetID?
  = link_to 'Yes',  new_northwestern_user_session_url, class: 'button'
  = link_to 'No',  new_external_user_session_url, class: 'button'

app/views/users/_navigation.html.haml
%ul.details.menu
  %li.repository{ class: active?('active', controller: 'repositories', action: ['edit', 'update']) }
    = link_to 'Details', edit_repository_url(@repository), { class: 'edit_repository_link' }
  %li.repository_content{ class: active?('active', controller: 'contents', action: ['edit', 'update']) }
    = link_to 'Content', edit_repository_content_url(@repository), { class: 'edit_repository_content_link' }
  %li.repository_users{ class: active?('active', controller: 'repository_users', action: 'index') }
    = link_to 'Users', repository_repository_users_url(@repository), { class: 'repository_repository_users_link' }
  %li.specimen_types{ class: active?('active', controller: 'specimen_types', action: ['index', 'bulk_update']) }
    = link_to 'Specimen Types', repository_specimen_types_url(@repository), { class: 'repository_specime_types_link' }

app/views/users/edit.html.haml
- content_for(:title) do
  Edit Profile

#edit_user
  %h4
    = "Profile"
  = form_for @user, html: { class: 'repository_form', multipart: true } do |f|
    = render 'repository', repository: @repository, f: f
    .navigation{class: 'small-offset-12 small-12 large-offset-20 large-4 columns' }
      %p.help-text
        %span{ class: 'required' }
        Indicates required field
      = f.submit 'Save', class: 'button'
      = link_to 'Cancel', repositories_url, class: 'cancel-link button warning'

app/views/users/login.html.haml
#disburser_login
  .row
    = render 'users/login'

app/views/users/show.html.haml
- content_for(:title) do
  User

#user
  .user_header
    %h4
      Profile
  .user
    .row
      .username
        %div{class: 'small-10 large-4 columns' }
          %label
            Username
        %div{class: 'small-14 large-20 columns' }
          = @user.username
    .row
      .first_name
        %div{class: 'small-10 large-4 columns' }
          %label
            First Name
        %div{class: 'small-14 large-20 columns' }
          = @user.first_name
    .row
      .last_name
        %div{class: 'small-10 large-4 columns' }
          %label
            Last Name
        %div{class: 'small-14 large-20 columns' }
          = @user.last_name
    .row
      .email
        %div{class: 'small-10 large-4 columns' }
          %label
            Email
        %div{class: 'small-14 large-20 columns' }
          = @user.email
    .row
      .actions{class: 'small-24 columns' }
        - if user_type?(@user, ExternalUser)
          = link_to 'Edit', edit_external_user_registration_url, class: 'button'