config/routes.rb
Rails.application.routes.draw do
  devise_for :external_users, controllers: { registrations: 'registrations' }
  devise_for :northwestern_users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'login', to: 'users#login'

  resources :disburser_requests, only: :index, path: 'requests' do
    collection do
      get :admin
      get :data_coordinator
      get :specimen_coordinator
      get :committee
    end

    member do
      get :edit_admin_status
      get :edit_committee_review
      get :edit_data_status
      get :edit_specimen_status
      patch :admin_status
      patch :data_status
      patch :specimen_status
      patch :cancel
    end
    resources :disburser_request_votes
  end

  resources :repositories do
    resources :repository_users
    resources :disburser_requests, except: :index, path: 'requests' do
      member do
        get :download_file
      end
    end
    resources :specimen_types, only: :index do
      collection do
        patch :bulk_update
      end
    end
    member do
      get :download_file
    end

    resource :content, only: [:edit, :update]
  end

  resources :users, only: [:index, :show]

  root 'home#index'
end

app/views/shared/_navigation.html.haml
#disburser_navigation
  .disburser_branding
    .row.expanded
      .disburser_title{ class: 'large-18 columns' }
        %h5
          Clinical Research Repository Disburser
        %h6
          Robert H. Lurie Comprehensive Cancer Center of Northwestern University
      .disburser_environment{ class: 'large-2 columns text-right' }
        - if Rails.env.development? || Rails.env.staging?
          %h3
            = "#{Rails.env.capitalize}"
      .disburser_logo{ class: 'large-4 columns text-right' }
        %a{ :href => 'http://cancer.northwestern.edu/home/index.cfm' }
          = image_tag('rhlccc_small_2.png', alt: 'Robert H. Lurie Comprehensive Cancer Center of Northwestern University')
  .off-canvas-wrapper
    .off-canvas-wrapper-inner{"data-off-canvas-wrapper" => ""}
      / off-canvas title bar for 'small' screen
      .title-bar{"data-hide-for" => "medium", "data-responsive-toggle" => "widemenu"}
        .title-bar-left
          %button.menu-icon{"data-open" => "offCanvasLeft", :type => "button"}
          %span.title-bar-title Disburser
        .title-bar-right
          %span.title-bar-title
          - if user_signed_in?
            Profile
          - else
            Login
          %button.menu-icon{"data-open" => "offCanvasRight", :type => "button"}
      / off-canvas left menu
      #offCanvasLeft.off-canvas.position-left{"data-off-canvas" => ""}
        %ul.vertical.menu
          = render 'shared/navigation_left'
      / off-canvas right menu
      #offCanvasRight.off-canvas.position-right{"data-off-canvas" => "", "data-position" => "right"}
        %ul.vertical.menu
          = render 'shared/navigation_right'
      / "wider" top-bar menu for 'medium' and up
      #widemenu.top-bar
        .top-bar-left
          %ul.menu
            = render 'shared/navigation_left'
        .top-bar-right
          %ul.menu
            = render 'shared/navigation_right'
      / original content goes in this container
      .off-canvas-content{"data-off-canvas-content" => ""}
        .flash.small-centered{ 'data-closable' => true }
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              = content_tag :div, class: "callout small #{name}" do
                %button.close-button{"aria-label" => "dismiss alert", "data-close" => "", :type => "button"}
                  %span{"aria-hidden" => "true"} ×
                = msg
        .row.column
          = yield

app/views/shared/_navigation_left.html.haml
%li.menu-text
  = link_to 'Home', root_url
- if user_signed_in?
  - if policy(Repository).index?
    %li.repositories.menu-text{ class: active?('active', controller: '/repositories', action: 'index') }
      = link_to "Repositories", repositories_url
  %li.requests.menu-text{ class: active?('active', controller: '/disburser_requests', action: 'index') }
    = link_to "Requests", disburser_requests_url
  - if policy(DisburserRequest).admin?
    %li.admin.menu-text{ class: active?('active', controller: '/disburser_requests', action: 'admin') }
      = link_to 'Admin', admin_disburser_requests_url
  - if policy(DisburserRequest).committee?
    %li.committee.menu-text{ class: active?('active', controller: '/disburser_requests', action: 'committee') }
      = link_to 'Committee', committee_disburser_requests_url
  - if policy(DisburserRequest).data_coordinator?
    %li.data_coordinator.menu-text{ class: active?('active', controller: '/disburser_requests', action: 'data_coordinator') }
      = link_to 'Data Coordinator', data_coordinator_disburser_requests_url
  - if policy(DisburserRequest).specimen_coordinator?
    %li.specimen_coordinator.menu-text{ class: active?('active', controller: '/disburser_requests', action: 'specimen_coordinator') }
      = link_to 'Specimen Coordinator', specimen_coordinator_disburser_requests_url

app/views/shared/_navigation_right.html.haml
- if user_signed_in?
  %li.profile.menu-text{ class: active?('active', controller: '/users', action: 'show', id: current_user.id) }
    = link_to "Profile (#{current_user.username})", user_url(current_user)
- else
  %li.login.menu-text
  %li.login.menu-text{ class: active?('active', controller: 'devise/sessions', action: 'new') }
    = link_to 'Login', login_path
%li.log_out.menu-text
  - if northwestern_user_signed_in?
    = link_to "Log out", destroy_northwestern_user_session_path, method: :delete
  - if external_user_signed_in?
    = link_to "Log out", destroy_external_user_session_path, method: :delete