config/routes.rb
Rails.application.routes.draw do
  devise_for :external_users, controllers: { registrations: 'registrations' }
  devise_for :northwestern_users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'login', to: 'users#login'

  resources :disburser_requests, only: :index, path: 'requests' do
    collection do
      get :admin
      get :data_coordinator
      get :specimen_coordinator
      get :committee
    end

    member do
      get :edit_admin_status
      get :edit_committee_review
      get :edit_data_status
      get :edit_specimen_status
      patch :admin_status
      patch :data_status
      patch :specimen_status
      patch :cancel
    end
    resources :disburser_request_votes
  end

  resources :repositories do
    resources :repository_users
    resources :disburser_requests, except: :index, path: 'requests' do
      member do
        get :download_file
      end
    end
    resources :specimen_types, only: :index do
      collection do
        patch :bulk_update
      end
    end
    member do
      get :download_file
    end

    resource :content, only: [:edit, :update]
  end

  resources :users, only: [:index, :show]

  root 'home#index'
end

app/controllers/disburser_requests_controller.rb
class DisburserRequestsController < ApplicationController
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction
  before_action :load_repository, only: [:new, :create, :edit, :update]
  before_action :load_disburser_request, only: [:edit, :update, :edit_admin_status, :edit_data_status, :edit_specimen_status, :download_file, :data_status, :specimen_status, :admin_status, :edit_committee_review, :committee_review, :cancel]
  before_action :load_specimen_types, only: [:new, :create, :edit, :update]

  def index
    params[:page]||= 1
    options = {}
    options[:sort_column] = sort_column
    options[:sort_direction] = sort_direction

    @repositories = Repository.is_public.order('name ASC')
    @disburser_requests = current_user.disburser_requests.by_repository(params[:repository_id]).by_feasibility(params[:feasibility]).by_status(params[:status]).by_data_status(params[:data_status]).by_specimen_status(params[:specimen_status]).search_across_fields(params[:search], options).paginate(per_page: 10, page: params[:page])
  end

  def admin
    authorize DisburserRequest
    params[:page]||= 1
    params[:feasibility]||= 'no'
    options = {}
    options[:sort_column] = sort_column
    options[:sort_direction] = sort_direction

    @repositories = Repository.all.order('name ASC')
    @disburser_requests = current_user.admin_disbursr_requests.by_repository(params[:repository_id]).by_feasibility(params[:feasibility]).by_status(params[:status]).by_data_status(params[:data_status]).by_specimen_status(params[:specimen_status]).search_across_fields(params[:search], options).paginate(per_page: 10, page: params[:page])
  end

  def data_coordinator
    authorize DisburserRequest
    params[:page]||= 1
    params[:data_status]||= DisburserRequest::DISBURSER_REQUEST_DATA_STATUS_NOT_STARTED
    options = {}
    options[:sort_column] = sort_column
    options[:sort_direction] = sort_direction

    @repositories = Repository.all.order('name ASC')
    @disburser_requests = current_user.data_coordinator_disbursr_requests.by_repository(params[:repository_id]).by_feasibility(params[:feasibility]).by_status(params[:status]).by_data_status(params[:data_status]).by_specimen_status(params[:specimen_status]).search_across_fields(params[:search], options).paginate(per_page: 10, page: params[:page])
  end

  def specimen_coordinator
    authorize DisburserRequest
    params[:page]||= 1
    params[:data_status]||= DisburserRequest::DISBURSER_REQUEST_DATA_STATUS_DATA_CHECKED
    params[:specimen_status]||= DisburserRequest::DISBURSER_REQUEST_SPECIMEN_STATUS_NOT_STARTED
    options = {}
    options[:sort_column] = sort_column
    options[:sort_direction] = sort_direction

    @repositories = Repository.all.order('name ASC')
    @disburser_requests = current_user.specimen_coordinator_disbursr_requests.by_repository(params[:repository_id]).by_feasibility(params[:feasibility]).by_status(params[:status]).by_data_status(params[:data_status]).by_specimen_status(params[:specimen_status]).search_across_fields(params[:search], options).paginate(per_page: 10, page: params[:page])
  end

  def committee
    authorize DisburserRequest
    params[:page]||= 1
    params[:status]||= DisburserRequest::DISBURSER_REQUEST_STATUS_COMMITTEE_REVIEW
    params[:vote_status]||= DisburserRequest::DISBURSER_REQUEST_VOTE_STATUS_PENDING_MY_VOTE
    options = {}
    options[:sort_column] = sort_column
    options[:sort_direction] = sort_direction

    @repositories = Repository.all.order('name ASC')
    @disburser_requests = current_user.committee_disburser_requests(status: params[:status]).by_repository(params[:repository_id]).by_vote_status(current_user, params[:vote_status]).search_across_fields(params[:search], options).paginate(per_page: 10, page: params[:page])
  end

  def new
    @disburser_request = @repository.disburser_requests.new(submitter: current_user)
    @disburser_request.disburser_request_details.new
  end

  def edit
    authorize @disburser_request
  end

  def create
    add_file_uload('methods_justifications')
    add_file_uload('custom_request_form')
    add_file_uload('supporting_document')

    @disburser_request = @repository.disburser_requests.build(disburser_request_params)

    remove_file_uload('methods_justifications')
    remove_file_uload('custom_request_form')
    remove_file_uload('supporting_document')

    @disburser_request.submitter = current_user
    @disburser_request.status_user = current_user

    if @disburser_request.save
      flash[:success] = 'You have successfully created a repository request.'
      redirect_to disburser_requests_url
    else
      flash.now[:alert] = 'Failed to create repository request.'
      render action: 'new'
    end
  end

  def update
    authorize @disburser_request
    remove_file_uload('methods_justifications')
    remove_file_uload('custom_request_form')
    remove_file_uload('supporting_document')

    @disburser_request.assign_attributes(disburser_request_params)
    @disburser_request.status_user = current_user

    if @disburser_request.save
      flash[:success] = 'You have successfully updated a repository request.'
      redirect_to disburser_requests_url
    else
      flash.now[:alert] = 'Failed to update repository request.'
      render action: 'edit'
    end
  end

  def download_file
    authorize @disburser_request
    case params[:file_type]
    when 'custom_request_form'
      file = @disburser_request.custom_request_form.path
    when 'methods_justifications'
      file = @disburser_request.methods_justifications.path
    when 'supporting_document'
      file = @disburser_request.supporting_document.path
    end

    return send_file file, disposition: 'attachment', x_sendfile: true unless file.blank?
  end

  def edit_admin_status
    authorize @disburser_request
    load_specimen_types_from_disburser_request
    @disburser_request.status_at = DateTime.now.to_s(:date)
    @disburser_request.data_status_status_at = DateTime.now.to_s(:date)
    @disburser_request.specimen_status_status_at = DateTime.now.to_s(:date)
  end

  def edit_committee_review
    authorize @disburser_request
    @disburser_request_vote = @disburser_request.find_or_initialize_disburser_request_vote(current_user)
  end

  def edit_data_status
    authorize @disburser_request
    @disburser_request.data_status_status_at = DateTime.now.to_s(:date)
  end

  def edit_specimen_status
    authorize @disburser_request
    @disburser_request.specimen_status_status_at = DateTime.now.to_s(:date)
  end

  def data_status
    authorize @disburser_request
    @disburser_request.assign_attributes(disburser_request_params)
    @disburser_request.status_user = current_user
    if @disburser_request.save
      flash[:success] = 'You have successfully updated the status of a repository request.'
      redirect_to data_coordinator_disburser_requests_url
    else
      @disburser_request.data_status_status_at = DateTime.now.to_s(:date)
      flash.now[:alert] = 'Failed to update the status of a repository request.'
      render action: 'edit_data_status'
    end
  end

  def specimen_status
    authorize @disburser_request
    @disburser_request.assign_attributes(disburser_request_params)
    @disburser_request.status_user = current_user
    if @disburser_request.save
      flash[:success] = 'You have successfully updated the status of a repository request.'
      redirect_to specimen_coordinator_disburser_requests_url
    else
      @disburser_request.specimen_status_status_at = DateTime.now.to_s(:date)
      flash.now[:alert] = 'Failed to update the status of a repository request.'
      render action: 'edit_specimen_status'
    end
  end

  def admin_status
    authorize @disburser_request
    load_specimen_types_from_disburser_request
    remove_file_uload('methods_justifications')
    remove_file_uload('custom_request_form')
    remove_file_uload('supporting_document')
    @disburser_request.assign_attributes(disburser_request_params)
    @disburser_request.status_user = current_user

    if @disburser_request.save
      flash[:success] = 'You have successfully updated the status of a repository request.'
      redirect_to admin_disburser_requests_url
    else
      @disburser_request.status_at = DateTime.now.to_s(:date)
      @disburser_request.data_status_status_at = DateTime.now.to_s(:date)
      @disburser_request.specimen_status_status_at = DateTime.now.to_s(:date)
      flash.now[:alert] = 'Failed to update the status of a repository request.'
      render action: 'edit_admin_status'
    end
  end

  def cancel
    authorize @disburser_request
    @disburser_request.status = DisburserRequest::DISBURSER_REQUEST_STATUS_CANCELED
    @disburser_request.status_user = current_user
    if @disburser_request.save
      flash[:success] = 'You have successfully canceled the repository request.'
      redirect_to disburser_requests_url
    else
      flash.now[:alert] = 'Failed to cancel the repository request.'
      redirect_to disburser_requests_url
    end
  end

  private
    def load_specimen_types_from_disburser_request
      @specimen_types = @disburser_request.repository.specimen_types.order('name ASC').map { |specimen_type| [specimen_type.name, specimen_type.id] }
    end

    def load_specimen_types
      @specimen_types = @repository.specimen_types.order('name ASC').map { |specimen_type| [specimen_type.name, specimen_type.id] }
    end

    def disburser_request_params
      params.require(:disburser_request).permit(:status_at, :data_status_status_at, :specimen_status_status_at, :data_status_comments, :specimen_status_comments, :status_comments, :specimen_name, :specimen_quantity, :specimen_type_id,
                                                :status, :data_status, :specimen_status, :title, :investigator, :irb_number, :feasibility, :cohort_criteria, :data_for_cohort, :methods_justifications, :methods_justifications_cache,

app/views/disburser_requests/_disburser_request.html.haml
.row
  .submitter{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_submitter' }
        Submitter
    %div{class: 'small-12 large-19 columns' }
      = @disburser_request.submitter.full_name
.row
  .submitter_email{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_submitter_email' }
        Submitter Email
    %div{class: 'small-12 large-19 columns' }
      = @disburser_request.submitter.email
.row
  .investigator{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_investigator' }
        Investigator
        %span{ class: 'validation required' }
    %div{class: 'small-12 large-19 columns' }
      = f.text_field :investigator
      - if validation_errors?(@disburser_request, :investigator)
        %p.error= format_validation_errors(@disburser_request, :investigator)
.row
  .title{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_title' }
        Project Title
        %span{ class: 'validation required' }
    %div{class: 'small-12 large-19 columns' }
      = f.text_field :title
      - if validation_errors?(@disburser_request, :title)
        %p.error= format_validation_errors(@disburser_request, :title)
.row
  .irb_number{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_irb_number' }
        IRB Number
        %span{ class: 'validation required' }
    %div{class: 'small-12 large-19 columns' }
      = f.text_field :irb_number
      - if validation_errors?(@disburser_request, :irb_number)
        %p.error= format_validation_errors(@disburser_request, :irb_number)
.row
  %fieldset{class: 'small-offset-5 small-19 columns' }
    = f.check_box :feasibility
    %label{for: 'disburser_request_feasibility'} Feasibility?
    %span{ id: 'feasibilityHelpText', class: 'help-text' }
      Only aggregate numbers will be provided for feasibility requests. No approved IRB protocol is required.
- if @disburser_request.use_custom_request_form
  .row
    .custom_request_form{class: 'small-24 columns' }
      %div{class: 'small-12 large-5 columns' }
        %label{for: 'disburser_request_custom_request_form' }
          Custom Request Form
          %span{ class: 'validation required' }
      %div{class: 'small-12 large-19 columns' }
        %div
          - if @disburser_request.custom_request_form? && !@disburser_request.new_record?
            = link_to download_file_repository_disburser_request_url(@disburser_request, file_type: 'custom_request_form'), 'data-turbolinks' => false, class: 'custom_request_form_url' do
              %i
              = @disburser_request.custom_request_form.file.filename
          - if @disburser_request.custom_request_form? && @disburser_request.new_record?
            = link_to @disburser_request.custom_request_form.identifier, "#{@disburser_request.custom_request_form.url}",  class: 'custom_request_form_url'
          = f.file_field :custom_request_form, class: "#{@disburser_request.custom_request_form? ? 'hide' : '' }"
          - if @disburser_request.custom_request_form_cache
            = f.hidden_field :custom_request_form_cache, value: @disburser_request.custom_request_form_cache
          - else
            = f.hidden_field :custom_request_form_cache, value: @disburser_request.custom_request_form
          = link_to 'Remove', '', 'data-turbolinks' => false,  class: "alert button tiny remove_custom_request_form_link #{@disburser_request.custom_request_form? ? '' : 'hide' }"
          - if validation_errors?(@disburser_request, :custom_request_form)
            %p.error= format_validation_errors(@disburser_request, :custom_request_form)
        %div
          = link_to download_file_repository_url(@disburser_request.repository, file_type: 'custom_request_form'), 'data-turbolinks' => false, class: 'custom_request_form_url' do
            %i.fi-download
              Custom Request Form (Download, fill out and attach back to this request.)
  = render 'supporting_document', disburser_request: @disburser_request, f: f
- else
  .row
    .methods_justifications{class: 'small-24 columns' }
      %div{class: 'small-12 large-5 columns' }
        %label{for: 'disburser_request_methods_justifications' }
          Methods/Justifications
          %span{ class: 'validation required' }
      %div{class: 'small-12 large-19 columns' }
        %div
          - if @disburser_request.methods_justifications? && !@disburser_request.new_record?
            = link_to download_file_repository_disburser_request_url(@disburser_request, file_type: 'methods_justifications'), 'data-turbolinks' => false, class: 'methods_justifications_url' do
              %i
              = @disburser_request.methods_justifications.file.filename
          - if @disburser_request.methods_justifications? && @disburser_request.new_record?
            = link_to @disburser_request.methods_justifications.identifier, "#{@disburser_request.methods_justifications.url}",  class: 'methods_justifications_url'
          = f.file_field :methods_justifications, class: "#{@disburser_request.methods_justifications? ? 'hide' : '' }"
          - if @disburser_request.methods_justifications_cache
            = f.hidden_field :methods_justifications_cache, value: @disburser_request.methods_justifications_cache
          - else
            = f.hidden_field :methods_justifications_cache, value: @disburser_request.methods_justifications
          = link_to 'Remove', '', 'data-turbolinks' => false,  class: "alert button tiny remove_methods_justifications_link #{@disburser_request.methods_justifications? ? '' : 'hide' }"
          - if validation_errors?(@disburser_request, :methods_justifications)
            %p.error= format_validation_errors(@disburser_request, :methods_justifications)
          %span{ id: 'methodsJustificationsHelpText', class: 'help-text' }
            Please provide a Methods/Justifications document scientifically justifying your receipt of data/specimens.
  = render 'supporting_document', disburser_request: @disburser_request, f: f
  .row
    .cohort_criteria{class: 'small-24 columns' }
      %label{for: 'disburser_request_cohort_criteria' }
        Cohort Criteria
        %span{ class: 'validation required' }
      = f.text_area :cohort_criteria, rows: 2
      - if validation_errors?(@disburser_request, :cohort_criteria)
        %p.error= format_validation_errors(@disburser_request, :cohort_criteria)
  .row
    .data_for_cohort{class: 'small-24 columns' }
      %label{for: 'disburser_request_data_for_cohort' }
        Data for cohort
        %span{ class: 'validation required' }
      = f.text_area :data_for_cohort, rows: 2
      - if validation_errors?(@disburser_request, :data_for_cohort)
        %p.error= format_validation_errors(@disburser_request, :data_for_cohort)
  .row
    .disburser_request_details{class: 'small-24 columns' }
      - if @disburser_request.repository.specimen_types.any?
        %b
          Specimens
        %table{ id: 'disburser_request_details' }
          %thead
            %tr
              %th.specimen_type{ width: 200 }
                Type
              %th.quantity{ width: 200 }
                Quantity
              %th.volume{ width: 200 }
                Volume
              %th.comments{ width: 200 }
                Comments
              %th.remove{ width: 100 }
          %tbody
            = f.fields_for :disburser_request_details do |disburser_request_detail|
              = render 'disburser_request_details/disburser_request_detail_fields', f: disburser_request_detail
        .links
          = link_to_add_association 'Add', f, :disburser_request_details, 'data-association-insertion-method' => 'append', 'data-association-insertion-node' => '#disburser_request_details tbody', partial: 'disburser_request_details/disburser_request_detail_fields', class: 'button tiny primary'

app/views/disburser_requests/_edit_status.html.haml
.row
  .submitter{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_submitter' }
        Submitter
    %div{class: 'small-12 large-19 columns' }
      = disburser_request.submitter.full_name
.row
  .submitter_email{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_submitter_email' }
        Submitter Email
    %div{class: 'small-12 large-19 columns' }
      = @disburser_request.submitter.email
.row
  .investigator{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_investigator' }
        Investigator
    %div{class: 'small-12 large-19 columns' }
      = disburser_request.investigator
.row
  .title{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_title' }
        Project Title
    %div{class: 'small-12 large-19 columns' }
      = disburser_request.title
.row
  .irb_number{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_irb_number' }
        IRB Number
    %div{class: 'small-12 large-19 columns' }
      = disburser_request.irb_number
.row
  .feasibility
    %fieldset{class: 'small-offset-5 small-19 columns' }
      = check_box_tag 'feasibility', disburser_request.feasibility, checked?(disburser_request.feasibility, true, true),  disabled: true
      %label{for: 'feasibility'} Feasibility?
- if @disburser_request.use_custom_request_form
  .row
    .custom_request_form{class: 'small-24 columns' }
      %div{class: 'small-12 large-5 columns' }
        %label{for: 'disburser_request_custom_request_form' }
          Custom Request Form
      %div{class: 'small-12 large-19 columns' }
        %div
          - if disburser_request.custom_request_form?
            = link_to download_file_repository_disburser_request_url(disburser_request.repository, disburser_request, file_type: 'custom_request_form'), 'data-turbolinks' => false, class: 'custom_request_form_url' do
              %i
                Custom Request Form
  = render '/disburser_requests/show_supporting_document', disburser_request: disburser_request
- else
  .row
    .methods_justifications{class: 'small-24 columns' }
      %div{class: 'small-12 large-5 columns' }
        %label{for: 'disburser_request_methods_justifications' }
          Methods/Justifications
      %div{class: 'small-12 large-19 columns' }
        %div
          - if disburser_request.methods_justifications?
            = link_to download_file_repository_disburser_request_url(disburser_request.repository, disburser_request, file_type: 'methods_justifications'), 'data-turbolinks' => false, class: 'methods_justifications_url' do
              %i
              = disburser_request.methods_justifications.file.filename
  = render '/disburser_requests/show_supporting_document', disburser_request: disburser_request
  .row
    .cohort_criteria{class: 'small-24 columns' }
      %label{for: 'cohort_criteria' }
        Cohort Criteria
      = text_area_tag :cohort_criteria, disburser_request.cohort_criteria, rows: 2, disabled: true

  .row
    .data_for_cohort{class: 'small-24 columns' }
      %label{for: 'data_for_cohort' }
        Data for cohort
      = text_area_tag :data_for_cohort, disburser_request.data_for_cohort, rows: 2, disabled: true
  .row
    .disburser_request_details{class: 'small-24 columns' }
      - if disburser_request.disburser_request_details.any?
        %table{ id: 'disburser_request_details' }
          %caption
            Specimens
          %thead
            %tr
              %th.specimen_type{ width: 200 }
                Type
              %th.quantity{ width: 200 }
                Quantity
              %th.volume{ width: 200 }
                Volume
              %th.comments{ width: 200 }
                Comments
          %tbody
            - disburser_request.disburser_request_details.each do |disburser_request_detail|
              = render 'disburser_request_details/disburser_request_detail_fields_show', disburser_request_detail: disburser_request_detail

app/views/disburser_requests/_show_supporting_document.html.haml
.row
  .supporting_document{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_supporting_document' }
        Supporting Document
    %div{class: 'small-12 large-19 columns' }
      %div
        - if disburser_request.supporting_document?
          = link_to download_file_repository_disburser_request_url(disburser_request.repository, disburser_request, file_type: 'supporting_document'), 'data-turbolinks' => false, class: 'supporting_document_url' do
            %i
            = disburser_request.supporting_document.file.filename

app/views/disburser_requests/_supporting_document.html.haml
.row
  .supporting_document{class: 'small-24 columns' }
    %div{class: 'small-12 large-5 columns' }
      %label{for: 'disburser_request_supporting_document' }
        Supporting Document
    %div{class: 'small-12 large-19 columns' }
      %div
        - if disburser_request.supporting_document? && !disburser_request.new_record?
          = link_to download_file_repository_disburser_request_url(disburser_request, file_type: 'supporting_document'), 'data-turbolinks' => false, class: 'supporting_document_url' do
            %i
            = disburser_request.supporting_document.file.filename
        - if disburser_request.supporting_document? && disburser_request.new_record?
          = link_to disburser_request.supporting_document.identifier, "#{disburser_request.supporting_document.url}",  class: 'supporting_document_url'
        = f.file_field :supporting_document, class: "#{disburser_request.supporting_document? ? 'hide' : '' }"
        - if disburser_request.supporting_document_cache
          = f.hidden_field :supporting_document_cache, value: disburser_request.supporting_document_cache
        - else
          = f.hidden_field :supporting_document_cache, value: disburser_request.supporting_document
        = link_to 'Remove', '', 'data-turbolinks' => false,  class: "alert button tiny remove_supporting_document_link #{disburser_request.supporting_document? ? '' : 'hide' }"
        - if validation_errors?(disburser_request, :supporting_document)
          %p.error= format_validation_errors(disburser_request, :supporting_document)
        %span{ id: 'supportingDocumentHelpText', class: 'help-text' }
          Provide a supporting document if needed.

app/views/disburser_requests/committee.html.haml
- content_for(:title) do
  Committee

#disburser_requests
  .disburser_requests_header
    %h4
      Committee
    %p
      To learn more about how to user Disburser as a committe member, check out the
      = link_to 'user guide.', '/disburser_committee_user_guide.pdf', target: '_blank'
    = form_tag committee_disburser_requests_url, method: 'get', id: 'search_disburser_requests_form'  do
      .repository{ class: 'large-4 columns' }
        %label{for: 'repository_id' }
          Repository
        = select_tag :repository_id, options_for_select(@repositories.map { |repository| [repository.name, repository.id] }, (params[:repository_id].blank? ? '' : params[:repository_id])), { include_blank: 'all', class: 'repository '}
      .status{ class: 'large-4 columns' }
        %label{for: 'status' }
          Status
        = select_tag :status, options_for_select(DisburserRequest::DISBURSER_REQUEST_STATUSES_REVIEWABLE.map { |status| [status, status] }, (params[:status].blank? ? '' : params[:status])), { include_blank: 'all', class: 'status'}
      .vote_status{ class: 'large-4 columns' }
        %label{for: 'vote_status' }
          Vote Status
        = select_tag :vote_status, options_for_select(DisburserRequest::DISBURSER_REQUEST_VOTE_STATUSES.map { |vote_status| [vote_status, vote_status] }, (params[:vote_status].blank? ? '' : params[:vote_status])), { include_blank: 'all', class: 'vote_status'}
      .search_box{ class: 'large-8 columns' }
        %label{for: 'search' }
          Search
        = text_field_tag :search, (params[:search].nil? ? '' : params[:search]), type: 'search'
      .search_buttons{ class: 'large-4 columns' }
        %button{ type: 'submit', id: 'search_disburser_requests_button', class: 'tiny button' }
          Search
        = link_to 'Clear', committee_disburser_requests_url
  .disburser_requests_list
    = will_paginate @disburser_requests, renderer: FoundationPagination::Rails
    %table.hack_stack
      %thead
        %tr
          %th.repository
            = sortable 'repositories.name', 'Repository'
          %th.submitted_at
            = sortable 'submitted_at', 'Submitted'
          %th.title
            = sortable 'title', 'Project Title'
          %th.submitter
            = sortable 'users.last_name', 'Submitter'
          %th.investigator
            = sortable 'investigator'
          %th.irb_number
            = sortable 'irb_number', 'IRB Number'
          %th.status
            = sortable 'status'
          %th.edit
      %tbody
        - @disburser_requests.each do |disburser_request|
          = content_tag_for(:tr, disburser_request) do
            %td.repository
              = disburser_request.repository.name
            %td.submitted_at
              = format_date(disburser_request.submitted_at)
            %td.title
              = disburser_request.title
            %td.submitter
              = disburser_request.submitter.full_name
            %td.investigator
              = disburser_request.investigator
            %td.irb_number
              = disburser_request.irb_number
            %td.status
              = disburser_request.status
            %td.edit
              = link_to 'Review', edit_committee_review_disburser_request_url(disburser_request), { class: 'edit_committee_review_disburser_request_link' }
    = will_paginate @disburser_requests, renderer: FoundationPagination::Rails

app/views/disburser_requests/edit.html.haml
- content_for(:title) do
  Request
#disburser_request
  .row
    %h4
      = "Request for: #{@disburser_request.repository.name}"
    - if policy(@disburser_request).cancel?
      = form_for [@repository, @disburser_request],  url: cancel_disburser_request_url(@disburser_request),  html: { class: 'disburser_request_form_cancel large-offset-18 large-offset-6'  } do |f|
        = f.submit 'Cancel Request', class: 'button alert',  data: { confirm: 'Are you sure you want to cancel this disbursement request?' }
    = form_for [@repository, @disburser_request], html: { class: 'disburser_request_form disburser_request_form_submitter', multipart: true  } do |f|
      %p.help-text
        %span{ class: 'required' }
        Indicates required field
      = render 'disburser_request', repository: @repository, f: f
      .row
        = render 'status_history', disburser_request: @disburser_request, width: 18, f: f, allow_edit: false
        .status_update{ class: 'large-6 columns' }
          - if @disburser_request.new_record? || @disburser_request.draft?
            %b
              Status
            %p.help-text
              %br
              'Submitted' will send your request for review.
            = f.radio_button :status, DisburserRequest::DISBURSER_REQUEST_STAUTS_DRAFT, checked: checked?(@disburser_request.status, DisburserRequest::DISBURSER_REQUEST_STAUTS_DRAFT, true)
            = f.label :status, 'Draft', value: DisburserRequest::DISBURSER_REQUEST_STAUTS_DRAFT
            = f.radio_button :status, DisburserRequest::DISBURSER_REQUEST_STATUS_SUBMITTED, checked: checked?(@disburser_request.status, DisburserRequest::DISBURSER_REQUEST_STATUS_SUBMITTED, false)
            = f.label :status, 'Submitted', value: DisburserRequest::DISBURSER_REQUEST_STATUS_SUBMITTED
          - else
            = f.hidden_field :status
            %b
              Statuses
            .status
              %b
                Status:
              = @disburser_request.status
            .data_status
              %b
                Data Status:
              = @disburser_request.data_status
            .specimen_status
              %b
                Specimen Status:
              = @disburser_request.specimen_status
          .navigation
            = f.submit 'Save', class: 'button'
            = link_to 'Cancel', disburser_requests_url, class: 'cancel-link button warning'